### PR TITLE
Dom remove graphql

### PR DESCRIPTION
**Pull request by terazus**
- remove the graphQL api usage
- added files + parsers for chemicals and organisms
- prevent chemicals to be used more then once for each experiment
- added python 3.11 support

### CODE REVIEW

**Comment by terazus** [comment]
Sorry, this still currently has a minor bug.

**Comment by knirirr** [comment]
I encountered a lot of warnings whilst running tests, e.g.

```
2023-02-23 10:52:22,234 [WARNING]: parse_chemicals.py(parse_chemicals:146) >> ptx_code cannot be nan for compound Cetylpyridinium chloride monohydrate
```

Is this expected?

**Comment by terazus** [comment]
> I encountered a lot of warnings whilst running tests, e.g.
> 
> ```
> 2023-02-23 10:52:22,234 [WARNING]: parse_chemicals.py(parse_chemicals:146) >> ptx_code cannot be nan for compound Cetylpyridinium chloride monohydrate
> ```
> 
> Is this expected?

Yes. There are inconsistencies in the data I pulled from the flat files and this let us know that some elements couldn't not be created in the database (in this case the ptx_code of Cetylpyridinium chloride monohydrate is NaN which is not allowed)
I log the warnings instead of letting the app crash.

**Review by knirirr — APPROVED** [review]
I can't see any issues other than what we've discussed here and elsewhere.

**Pull request merged**
